// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Shared.SS220.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class LocalPartyInvitesWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private int _invitesLimit;

    private static readonly Thickness LocalPartyInvitePanelThickness = new(5);

    private static readonly TimeSpan DefaultFailReasonShowTime = TimeSpan.FromSeconds(10);
    private static readonly Color FailReasonColor = Color.Red;

    private readonly Dictionary<PartyInvite, LocalPartyInviteEntry> _entries = [];

    public LocalPartyInvitesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultInnerBackgroundColor };
        InputLine.PlaceHolder = Loc.GetString("ui-local-party-invites-window-inputline-placeholder");
        InviteButton.OnPressed += _ => SendInvite();

        Refresh();
    }

    public void Refresh()
    {
        InvitesContainer.DisposeAllChildren();
        _entries.Clear();
        if (_party.LocalParty is not { } party)
            return;

        var invites = party.Invites;

        var invitesCountInfo = Loc.GetString("ui-local-party-invites-window-sended-invites-count", ("count", invites.Count), ("limit", _invitesLimit));
        InvitesCountLabel.Text = invitesCountInfo;

        foreach (var invite in invites)
        {
            var entry = new LocalPartyInviteEntry(invite)
            {
                Margin = LocalPartyInvitePanelThickness
            };
            _entries.Add(invite, entry);
            InvitesContainer.AddChild(entry);
        }
    }

    public bool TryGetEntry(PartyInvite invite, [NotNullWhen(true)] out LocalPartyInviteEntry? entry)
    {
        return _entries.TryGetValue(invite, out entry);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _cfg.OnValueChanged(CCVars220.PartyInvitesLimit, OnInvitesLimitChanged, true);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _cfg.UnsubValueChanged(CCVars220.PartyInvitesLimit, OnInvitesLimitChanged);
    }

    private async void SendInvite()
    {
        var text = InputLine.Text;
        if (string.IsNullOrEmpty(text))
            return;

        var responce = await _party.InviteUserRequestAsync(text);
        if (responce.Timeout)
        {
            AddFailReason(Loc.GetString("ui-local-party-invites-window-send-failreason-timeout"));
            return;
        }

        if (!responce.Success)
        {
            AddFailReason(responce.Text);
            return;
        }
    }

    private void OnInvitesLimitChanged(int value)
    {
        _invitesLimit = value;
        Refresh();
    }

    private void AddFailReason(string reason, TimeSpan? showTime = null)
    {
        showTime ??= DefaultFailReasonShowTime;

        var msg = new FormattedMessage();
        msg.PushColor(FailReasonColor);
        msg.AddText(reason);
        msg.Pop();

        FailReasonLabel.SetMessage(msg);

        RemoveFailReason((int)showTime.Value.TotalMilliseconds);
    }

    private async void RemoveFailReason(int delay)
    {
        await Task.Delay(delay);

        FailReasonLabel.Text = null;
    }
}
