// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class PartySettingsWindow : DefaultWindow
{
    [Dependency] private readonly IPartyManager _party = default!;

    public PartySettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AcceptButton.OnPressed += _ =>
        {
            var settings = SettingsPanel.GetSettingsState();
            _party.SetSettingsRequest(settings);
            Close();
        };

        OnOpen += SettingsPanel.Refresh;
    }
}
