// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.SpaceWars.Party.UI.Tabs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class PartyWindow : DefaultWindow
{
    public PartyWindow()
    {
        RobustXamlLoader.Load(this);

        Tabs.SetTabTitle(0, Loc.GetString("ui-party-main-tab-name"));
        Tabs.SetTabTitle(1, Loc.GetString("ui-received-invites-tab-name"));

        Refresh();
    }

    protected override void Opened()
    {
        Refresh();
    }

    public void Refresh()
    {
        MainTab.Refresh();
        ReceivedInvitesTab.Refresh();
    }
}
