using Content.Client.SS220.SpaceWars.Party.UI.Tabs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.SpaceWars.Party.UI;

[GenerateTypedNameReferences]
public sealed partial class PartyMenu : DefaultWindow
{
    [Dependency] private readonly IPartyManager _partyManager = default!;

    public PartyMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _partyManager.OnPartyDataUpdated += _ => Update();
    }

    public void Update()
    {
        MainTab.Update();
    }
}
