// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Numerics;
using Content.Client.SS220.SpaceWars.Party.UI.CustomControls;
using Content.Client.SS220.UserInterface.Utility;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.SS220.SpaceWars.Party.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ReceivedPartyInvitesTab : Control
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly QuickConfirmationWindow _confirmationWindow = new();
    private readonly Dictionary<PartyInvite, ReceivedPartyInviteEntry> _entries = [];

    private static readonly Vector2 ConfirmationWindowSize = new(400, 80);

    public ReceivedPartyInvitesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InvitesPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultInnerBackgroundColor };

        ReceiveInvitesCheckbox.OnToggled += button =>
        {
            _party.SetReceiveInvitesStatus(button.Pressed);
        };

        _confirmationWindow.SetSize = ConfirmationWindowSize;

        Refresh();
    }

    public void Refresh()
    {
        InvitesContainer.RemoveAllChildren();
        _entries.Clear();

        foreach (var invite in _party.ReceivedInvites)
            AddInvite(invite);
    }

    public void AddInvite(PartyInvite invite)
    {
        if (invite.Target != _player.LocalUser)
            return;

        if (_entries.ContainsKey(invite))
            return;

        DebugTools.Assert(_party.ReceivedInvites.Contains(invite));

        var panel = new ReceivedPartyInviteEntry(invite)
        {
            Margin = new Thickness(5)
        };

        InvitesContainer.AddChild(panel);
        _entries.Add(invite, panel);

        UpdateInvitesCountLabel();
    }

    public void RemoveInvite(PartyInvite invite)
    {
        if (!_entries.TryGetValue(invite, out var panel))
            return;

        DebugTools.Assert(!_party.ReceivedInvites.Contains(invite));

        InvitesContainer.RemoveChild(panel);
        _entries.Remove(invite);

        UpdateInvitesCountLabel();
    }

    public bool TryGetEntry(PartyInvite invite, [NotNullWhen(true)] out ReceivedPartyInviteEntry? entry)
    {
        return _entries.TryGetValue(invite, out entry);
    }

    private void UpdateInvitesCountLabel()
    {
        var count = _entries.Count;
        InvitesCountLabel.Text = Loc.GetString("ui-received-invites-tab-invites-count-label", ("count", count));
    }
}
