using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.UserInterface.Utility;

[GenerateTypedNameReferences]
public sealed partial class QuickConfirmationWindow : DefaultWindow
{
    public event Action? OnConfirmed;
    public event Action? OnCanselled;

    private bool _confirmed = false;

    public QuickConfirmationWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Confirm();
        CancelButton.OnPressed -= _ => Close();
    }

    public QuickConfirmationWindow(string message) : this()
    {
        SetMessage(message);
    }

    public void ClearEvents()
    {
        OnConfirmed = null;
        OnCanselled = null;
    }

    public void SetMessage(string message)
    {
        MessageLabel.SetMessage(message);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _confirmed = false;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        if (!_confirmed)
            OnCanselled?.Invoke();
    }

    private void Confirm()
    {
        _confirmed = true;
        OnConfirmed?.Invoke();

        Close();
    }
}
