// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.Message;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class LocalPartyInviteEntry : PanelContainer
{
    [Dependency] private readonly IPartyManager _party = default!;

    public readonly PartyInvite Invite;

    public LocalPartyInviteEntry(PartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DebugTools.AssertEqual(_party.LocalParty?.Invites.Contains(invite), true);
        DebugTools.AssertEqual(_party.LocalParty?.Id, invite.PartyId);

        Invite = invite;

        CancelButton.OnPressed += _ => _party.DeleteLocalPartyInviteRequest(Invite.Id);

        PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultBackgroundColor };
        Refresh();
    }

    public void Refresh()
    {
        var receiverName = !string.IsNullOrEmpty(Invite.TargetName) ? Invite.TargetName : "unknown";
        ReceiverLabel.SetMarkup(Loc.GetString("ui-local-party-invite-panel-receiver-label", ("receiver", receiverName)));

        var status = SharedPartyManager.GetPartyInviteStatusName(Invite.Status);
        StatusLabel.SetMarkup(Loc.GetString("ui-local-party-invite-panel-status-label", ("status", status)));
    }
}
