// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Shared.SS220.CCVars;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class PartySettingsPanel : PanelContainer
{
    public event Action<PartySettingsState>? OnSettingChanged;

    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private int _partyMembersLimit;

    public PartySettingsPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Refresh();
    }

    public void Refresh()
    {
        MembersLimitLineEdit.SetText((_party.LocalParty?.Settings.MembersLimit ?? _partyMembersLimit).ToString());
    }

    public PartySettingsState GetSettingsState()
    {
        var state = new PartySettingsState();
        if (int.TryParse(MembersLimitLineEdit.Text, out var membersLimit))
            state.MembersLimit = membersLimit;

        return state;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _cfg.OnValueChanged(CCVars220.PartyInvitesLimit, OnPartyMembersLimitChanged, true);
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _cfg.UnsubValueChanged(CCVars220.PartyInvitesLimit, OnPartyMembersLimitChanged);
    }

    private void OnPartyMembersLimitChanged(int value)
    {
        _partyMembersLimit = value;
        Refresh();
    }
}
