// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.Resources;
using Content.Client.SS220.StyleTools;
using Content.Client.Stylesheets;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class PartyMemberEntry : PanelContainer
{
    [Dependency] private readonly IResourceCache _cache = default!;
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IStylesheetManager _stylesheetManager = default!;

    public readonly PartyMember Member;

    private const string FontResourcePath = "/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf";
    private const int FontSize = 11;

    private static readonly Vector2 ConnectionStatusIconScale = new(0.6f, 0.6f);
    private const string ConnectionStatusIconTexturePath = "/Textures/SS220/SpaceWars/Interface/Default/circle.svg.png";
    private static readonly Color ConnectionStatusIconConnectedColor = Color.Green;
    private static readonly Color ConnectionStatusIconDisconnectedColor = Color.Red;

    private static readonly Dictionary<PartyMemberRole, Color> RolesColor = new()
    {
        {PartyMemberRole.Member, new Color(52, 101, 131)},
        {PartyMemberRole.Host, new Color(146, 122, 25)}
    };

    public PartyMemberEntry(PartyMember member)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Stylesheet = new PartyMemberPanelStyle().Create(_stylesheetManager.SheetNano, _cache);

        Member = member;

        PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultBackgroundColor };
        var textFont = new VectorFont(_cache.GetResource<FontResource>(FontResourcePath), FontSize);

        UsernameLabel.FontOverride = textFont;
        PartyRoleLabel.FontOverride = textFont;
        ConnectionStatusLabel.FontOverride = textFont;

        ConnectionStatusIcon.TexturePath = ConnectionStatusIconTexturePath;
        ConnectionStatusIcon.TextureScale = ConnectionStatusIconScale;

        var setHostButtonTooltip = new Tooltip();
        setHostButtonTooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("ui-party-main-tab-set-host-button-tooltip")));
        SetHostButton.TooltipSupplier = _ => setHostButtonTooltip;
        SetHostButton.OnPressed += _ => _party.SetPartyHostRequest(member.UserId);
        SetHostButton.AddStyleClass(PartyMemberPanelStyle.SetHostButtonClass);

        var kickButtonTooltip = new Tooltip();
        kickButtonTooltip.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("ui-party-main-tab-kick-button-tooltip")));
        KickButton.TooltipSupplier = _ => kickButtonTooltip;
        KickButton.OnPressed += _ => _party.KickFromPartyRequest(member.UserId);

        Refresh();
    }

    public void Refresh()
    {
        UsernameLabel.Text = Member.Username;
        PartyRoleLabel.Text = SharedPartyManager.GetPartyMemberRoleName(Member.Role);

        var roleBackground = GetRoleColor(Member.Role);
        if (roleBackground != null)
            PartyRolePanel.PanelOverride = new StyleBoxFlat() { BackgroundColor = roleBackground.Value };

        ConnectionStatusIcon.ModulateSelfOverride = Member.Connected ? ConnectionStatusIconConnectedColor : ConnectionStatusIconDisconnectedColor;
        ConnectionStatusLabel.Text = Member.Connected
            ? Loc.GetString("ui-party-member-panel-member-connected")
            : Loc.GetString("ui-party-member-panel-member-disconnected");

        var hostButtonsVisible = _party.IsLocalPartyHost && Member.Role is not PartyMemberRole.Host;
        SetHostButton.Visible = hostButtonsVisible;
        KickButton.Visible = hostButtonsVisible;
    }

    private static Color? GetRoleColor(PartyMemberRole role)
    {
        RolesColor.TryGetValue(role, out var color);
        return color;
    }

    private sealed class PartyMemberPanelStyle : QuickStyle
    {
        public const string SetHostButtonClass = "setHostButton";
        private const string SetHostButtonTexture = "/Textures/SS220/SpaceWars/Interface/Party/up_arrow.svg.png";

        private static readonly Color SetHostButtonDefaultColor = Color.FromHex("#4B596A");
        private static readonly Color SetHostButtonHoverColor = Color.FromHex("#7F3636");
        private static readonly Color SetHostButtonPressedColor = Color.FromHex("#753131");

        protected override void CreateRules()
        {
            Builder.Element<TextureButton>()
                .Class(SetHostButtonClass)
                .Prop(TextureButton.StylePropertyTexture, Resources.GetTexture(SetHostButtonTexture))
                .Prop(StylePropertyModulateSelf, SetHostButtonDefaultColor);

            Builder.Element<TextureButton>()
                .Class(SetHostButtonClass)
                .Pseudo(TextureButton.StylePseudoClassHover)
                .Prop(StylePropertyModulateSelf, SetHostButtonHoverColor);

            Builder.Element<TextureButton>()
                .Class(SetHostButtonClass)
                .Pseudo(TextureButton.StylePseudoClassPressed)
                .Prop(StylePropertyModulateSelf, SetHostButtonPressedColor);
        }
    }
}
