// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using Content.Client.SS220.UserInterface.Utility;
using Content.Shared.SS220.SpaceWars.Party;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.SS220.SpaceWars.Party.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class ReceivedPartyInviteEntry : PanelContainer
{
    [Dependency] private readonly IPartyManager _party = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    public readonly PartyInvite Invite;
    private readonly QuickConfirmationWindow _confirmationWindow = new();

    public ReceivedPartyInviteEntry(PartyInvite invite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        DebugTools.Assert(_party.ReceivedInvites.Contains(invite));
        DebugTools.AssertEqual(invite.Target, _player.LocalUser);
        Invite = invite;

        AcceptButton.OnPressed += _ => Accept();
        DenyButton.OnPressed += _ => Deny();

        PanelOverride = new StyleBoxFlat { BackgroundColor = PartyUIController.DefaultBackgroundColor };

        Refresh();
    }

    public void Refresh()
    {
        SenderLabel.Text = Loc.GetString("ui-received-invite-panel-sender-label", ("sendername", Invite.SenderName));
    }

    private void Accept()
    {
        if (_party.LocalMember is { } member)
        {
            _confirmationWindow.ClearEvents();

            var message = member.Role switch
            {
                PartyMemberRole.Host => Loc.GetString("ui-received-invite-tab-leave-party-warning-host"),
                _ => Loc.GetString("ui-received-invite-tab-leave-party-warning")
            };

            _confirmationWindow.SetMessage(message);
            _confirmationWindow.OnConfirmed += () => _party.AcceptReceivedInviteRequest(Invite.Id);
            _confirmationWindow.OpenCentered();
        }
        else
            _party.AcceptReceivedInviteRequest(Invite.Id);
    }

    private void Deny()
    {
        _party.DenyReceivedInviteRequest(Invite.Id);
    }
}
